@startuml
interface InterpretabilityBase {
    <<abstract>> explain()
    <<abstract>> plot()
}
class FeatureAttribution {
<<abstract>> explain()
plot()
}
class Saliency_Base {
<<abstract>> explain()
plot()
    
}

class Perturbation {

}
class Surrogate {

}
class LEFTIST{
explain()
}
class TSR{
explain()
}
class InstanceBase {
<<abstract>> explain()
plot()
}

class Counterfactual {
<<abstract>> explain()
plot ()
plot_multi()
}
class AtesCF{
explain()
}

class NativeGuideCF{
explain()
}

class CEM {

}
class Anchor {
}

InterpretabilityBase --> FeatureAttribution
InterpretabilityBase --> InstanceBase
FeatureAttribution --> Saliency_Base
Saliency_Base --> TSR
FeatureAttribution --> Perturbation
FeatureAttribution --> Surrogate
InstanceBase --> Counterfactual 
InstanceBase -->  CEM
InstanceBase --> Anchor
Perturbation --> LEFTIST
Counterfactual --> AtesCF
Counterfactual --> NativeGuideCF
@enduml